# Copyright 2019 Canonical Ltd.  All rights reserved.

{%- if kafka_brokers %}
kafka-brokers: {{ kafka_brokers }}
{%- endif %}
{%- if kafka_tls %}
kafka-tls:
  ca-cert: {{ kafka_tls.cacert }}
  cert: {{ kafka_tls.cert }}
  key: {{ kafka_tls.key }}
{%- endif %}
{%- if influx_db %}
influx-db: {{ influx_db }}
{%- endif %}
{%- if topics_yaml %}
topics: 
{{ topics_yaml }}
{%- endif %}

