dist: bionic
language: go
go:
- 1.12
before_install:
# Install and set up LXD
- sudo apt remove -y --purge lxd lxd-client
- sudo snap install lxd
- sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment'
- sudo lxd waitready;
- sudo lxd init --auto;
- sudo usermod -a -G lxd travis;
# Install other build dependencies
- sudo snap install charm --classic
- sudo snap install snapcraft --classic
- sudo apt-get install -y build-essential flake8
install:
- git config --global --unset protocol.version  # https://github.com/juju/charm-tools/issues/532
- make lint
- GOPATH=$(mktemp -d) go test ./...
- sudo su travis -c make
