dist: bionic
language: go
go:
- 1.12
before_install:
- sudo snap install snapcraft --classic
- sudo apt-get install -y build-essential flake8
install:
- make lint
- GOPATH=$(mktemp -d) go test ./...
- make 
