dist: bionic
language: go
go:
- 1.12
before_install:
- sudo apt remove -y --purge lxd lxd-client
- sudo snap install lxd;
- sudo sh -c 'echo PATH=/snap/bin:$PATH >> /etc/environment';
- sudo lxd waitready;
- sudo lxd init --auto;
- sudo usermod -a -G lxd travis;
- sudo snap install snapcraft --classic
- sudo apt-get install -y build-essential flake8
install:
- make lint
- GOPATH=$(mktemp -d) go test ./...
- sudo su travis -c make
